config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'report/index'

  get 'report/student'

  get 'report/management'

  get 'exam/index'

  get 'exam/seating'

  get 'exam/eligibility'

  get 'welcome/index'

  post 'report/getStudent' => "report#getStudent"

  resources :extracurriculars
  resources :attendances
  resources :marks
  resources :subjects
  resources :teachers
  resources :students
  resources :cls

  root 'welcome#index'

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
	belongs_to :student
end

app/models/cl.rb
class Cl < ActiveRecord::Base
	belongs_to :teacher, inverse_of: :cl
	has_many :subjects, inverse_of: :cl
	has_many :students, inverse_of: :cl
end

app/models/extracurricular.rb
class Extracurricular < ActiveRecord::Base
	belongs_to :student, inverse_of: :extracurriculars
end

app/models/mark.rb
class Mark < ActiveRecord::Base
	belongs_to :student, inverse_of: :marks
	belongs_to :subject, inverse_of: :mark
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :extracurriculars, inverse_of: :student
	has_many :marks, inverse_of: :student
	
	belongs_to :cl, inverse_of: :students
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	belongs_to :teacher, inverse_of: :subjects
	belongs_to :cl, inverse_of: :subjects
	has_one :mark, inverse_of: :subject
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	has_one :cl, inverse_of: :teacher
	has_many :subjects, inverse_of: :teacher
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/cls_controller.rb
class ClsController < ApplicationController
  before_action :set_cl, only: [:show, :edit, :update, :destroy]

  # GET /cls
  # GET /cls.json
  def index
    @cls = Cl.all
  end

  # GET /cls/1
  # GET /cls/1.json
  def show
  end

  # GET /cls/new
  def new
    @cl = Cl.new
  end

  # GET /cls/1/edit
  def edit
  end

  # POST /cls
  # POST /cls.json
  def create
    @cl = Cl.new(cl_params)

    respond_to do |format|
      if @cl.save
        format.html { redirect_to @cl, notice: 'Cl was successfully created.' }
        format.json { render :show, status: :created, location: @cl }
      else
        format.html { render :new }
        format.json { render json: @cl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cls/1
  # PATCH/PUT /cls/1.json
  def update
    respond_to do |format|
      if @cl.update(cl_params)
        format.html { redirect_to @cl, notice: 'Cl was successfully updated.' }
        format.json { render :show, status: :ok, location: @cl }
      else
        format.html { render :edit }
        format.json { render json: @cl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cls/1
  # DELETE /cls/1.json
  def destroy
    @cl.destroy
    respond_to do |format|
      format.html { redirect_to cls_url, notice: 'Cl was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cl
      @cl = Cl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cl_params
      params.require(:cl).permit(:id, :std, :sec, :teacher_id, :room)
    end
end

app/controllers/exam_controller.rb
class ExamController < ApplicationController
  def index
    	@cls_teacher = Teacher.joins(:cl)
  end

  def seating
  end

  def eligibility
  end
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  before_action :set_mark, only: [:show, :edit, :update, :destroy]

  # GET /marks
  # GET /marks.json
  def index
    @marks = Mark.all
  end

  # GET /marks/1
  # GET /marks/1.json
  def show
  end

  # GET /marks/new
  def new
    @mark = Mark.new
  end

  # GET /marks/1/edit
  def edit
  end

  # POST /marks
  # POST /marks.json
  def create
    @mark = Mark.new(mark_params)

    respond_to do |format|
      if @mark.save
        format.html { redirect_to @mark, notice: 'Mark was successfully created.' }
        format.json { render :show, status: :created, location: @mark }
      else
        format.html { render :new }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marks/1
  # PATCH/PUT /marks/1.json
  def update
    respond_to do |format|
      if @mark.update(mark_params)
        format.html { redirect_to @mark, notice: 'Mark was successfully updated.' }
        format.json { render :show, status: :ok, location: @mark }
      else
        format.html { render :edit }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marks/1
  # DELETE /marks/1.json
  def destroy
    @mark.destroy
    respond_to do |format|
      format.html { redirect_to marks_url, notice: 'Mark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mark
      @mark = Mark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mark_params
      params.require(:mark).permit(:id,:student_id, :subject_id, :quarter, :half, :ann)
    end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  def index
  	@students = Student.all
  	@std_attd = Student.joins('join attendances ON students.sid = attendances.sid')
  	
  end

  def student
  	@students = Student.all
  end

  def management
  end

  def getStudent
  	sid = params[:sid]
  	print sid
  	
  	@student = Student.find(sid)
    @std = Student.joins(:marks)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/cls_helper.rb
module ClsHelper
end

app/helpers/exam_helper.rb
module ExamHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cls/_form.html.erb
<%= form_for(@cl) do |f| %>
  <% if @cl.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cl.errors.count, "error") %> prohibited this cl from being saved:</h2>

      <ul>
      <% @cl.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :std %><br>
    <%= f.number_field :std %>
  </div>
  <div class="field">
    <%= f.label :sec %><br>
    <%= f.text_field :sec %>
  </div>
  <div class="field">
    <%= f.label :teacher_id %><br>
    <%= f.number_field :teacher_id %>
  </div>
  <div class="field">
    <%= f.label :room %><br>
    <%= f.text_field :room %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cls/edit.html.erb
<h1>Editing Cl</h1>

<%= render 'form' %>

<%= link_to 'Show', @cl %> |
<%= link_to 'Back', cls_path %>

app/views/cls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cls</h1>

<table>
  <thead>
    <tr>
      <th>Cid</th>
      <th>Std</th>
      <th>Sec</th>
      <th>teacher_id</th>
      <th>Room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cls.each do |cl| %>
      <tr>
        <td><%= cl.id %></td>
        <td><%= cl.std %></td>
        <td><%= cl.sec %></td>
        <td><%= cl.teacher_id %></td>
        <td><%= cl.room %></td>
        <td><%= link_to 'Show', cl %></td>
        <td><%= link_to 'Edit', edit_cl_path(cl) %></td>
        <td><%= link_to 'Destroy', cl, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cl', new_cl_path %>

app/views/cls/new.html.erb
<h1>New Cl</h1>

<%= render 'form' %>

<%= link_to 'Back', cls_path %>

app/views/cls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cid:</strong>
  <%= @cl.id %>
</p>

<p>
  <strong>Std:</strong>
  <%= @cl.std %>
</p>

<p>
  <strong>Sec:</strong>
  <%= @cl.sec %>
</p>

<p>
  <strong>Tid:</strong>
  <%= @cl.teacher_id %>
</p>

<p>
  <strong>Room:</strong>
  <%= @cl.room %>
</p>

<%= link_to 'Edit', edit_cl_path(@cl) %> |
<%= link_to 'Back', cls_path %>

app/views/marks/_form.html.erb
<%= form_for(@mark) do |f| %>
  <% if @mark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mark.errors.count, "error") %> prohibited this mark from being saved:</h2>

      <ul>
      <% @mark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.number_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :subject_id %><br>
    <%= f.number_field :subject_id %>
  </div>
  <div class="field">
    <%= f.label :quarter %><br>
    <%= f.number_field :quarter %>
  </div>
  <div class="field">
    <%= f.label :half %><br>
    <%= f.number_field :half %>
  </div>
  <div class="field">
    <%= f.label :ann %><br>
    <%= f.number_field :ann %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/marks/edit.html.erb
<h1>Editing Mark</h1>

<%= render 'form' %>

<%= link_to 'Show', @mark %> |
<%= link_to 'Back', marks_path %>

app/views/marks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Marks</h1>

<table>
  <thead>
    <tr>
      <th>Student_id</th>
      <th>Subject_id</th>
      <th>Quarter</th>
      <th>Half</th>
      <th>Ann</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @marks.each do |mark| %>
      <tr>
        <td><%= mark.student_id %></td>
        <td><%= mark.subject_id %></td>
        <td><%= mark.quarter %></td>
        <td><%= mark.half %></td>
        <td><%= mark.ann %></td>
        <td><%= link_to 'Show', mark %></td>
        <td><%= link_to 'Edit', edit_mark_path(mark) %></td>
        <td><%= link_to 'Destroy', mark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mark', new_mark_path %>

app/views/marks/new.html.erb
<h1>New Mark</h1>

<%= render 'form' %>

<%= link_to 'Back', marks_path %>

app/views/marks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sid:</strong>
  <%= @mark.student_id %>
</p>

<p>
  <strong>Sub:</strong>
  <%= @mark.subject_id %>
</p>

<p>
  <strong>Quarter:</strong>
  <%= @mark.quarter %>
</p>

<p>
  <strong>Half:</strong>
  <%= @mark.half %>
</p>

<p>
  <strong>Ann:</strong>
  <%= @mark.ann %>
</p>

<%= link_to 'Edit', edit_mark_path(@mark) %> |
<%= link_to 'Back', marks_path %>