config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'report/index'

  get 'report/student'

  get 'report/management'

  get 'exam/index'

  get 'exam/seating'

  get 'exam/eligibility'

  get 'welcome/index'

  post 'report/getStudent' => "report#getStudent"

  resources :extracurriculars
  resources :attendances
  resources :marks
  resources :subjects
  resources :teachers
  resources :students
  resources :cls

  root 'welcome#index'

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
	belongs_to :student
end

app/models/cl.rb
class Cl < ActiveRecord::Base
	belongs_to :teacher, inverse_of: :cl
	has_many :subjects, inverse_of: :cl
	has_many :students, inverse_of: :cl
end

app/models/extracurricular.rb
class Extracurricular < ActiveRecord::Base
	belongs_to :student, inverse_of: :extracurriculars
end

app/models/mark.rb
class Mark < ActiveRecord::Base
	belongs_to :student, inverse_of: :marks
	belongs_to :subject, inverse_of: :mark
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :extracurriculars, inverse_of: :student
	has_many :marks, inverse_of: :student
	
	belongs_to :cl, inverse_of: :students
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	belongs_to :teacher, inverse_of: :subjects
	belongs_to :cl, inverse_of: :subjects
	has_one :mark, inverse_of: :subject
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	has_one :cl, inverse_of: :teacher
	has_many :subjects, inverse_of: :teacher
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/cls_controller.rb
class ClsController < ApplicationController
  before_action :set_cl, only: [:show, :edit, :update, :destroy]

  # GET /cls
  # GET /cls.json
  def index
    @cls = Cl.all
  end

  # GET /cls/1
  # GET /cls/1.json
  def show
  end

  # GET /cls/new
  def new
    @cl = Cl.new
  end

  # GET /cls/1/edit
  def edit
  end

  # POST /cls
  # POST /cls.json
  def create
    @cl = Cl.new(cl_params)

    respond_to do |format|
      if @cl.save
        format.html { redirect_to @cl, notice: 'Cl was successfully created.' }
        format.json { render :show, status: :created, location: @cl }
      else
        format.html { render :new }
        format.json { render json: @cl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cls/1
  # PATCH/PUT /cls/1.json
  def update
    respond_to do |format|
      if @cl.update(cl_params)
        format.html { redirect_to @cl, notice: 'Cl was successfully updated.' }
        format.json { render :show, status: :ok, location: @cl }
      else
        format.html { render :edit }
        format.json { render json: @cl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cls/1
  # DELETE /cls/1.json
  def destroy
    @cl.destroy
    respond_to do |format|
      format.html { redirect_to cls_url, notice: 'Cl was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cl
      @cl = Cl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cl_params
      params.require(:cl).permit(:id, :std, :sec, :teacher_id, :room)
    end
end

app/controllers/exam_controller.rb
class ExamController < ApplicationController
  def index
    	@cls_teacher = Teacher.joins(:cl)
  end

  def seating
  end

  def eligibility
  end
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  before_action :set_mark, only: [:show, :edit, :update, :destroy]

  # GET /marks
  # GET /marks.json
  def index
    @marks = Mark.all
  end

  # GET /marks/1
  # GET /marks/1.json
  def show
  end

  # GET /marks/new
  def new
    @mark = Mark.new
  end

  # GET /marks/1/edit
  def edit
  end

  # POST /marks
  # POST /marks.json
  def create
    @mark = Mark.new(mark_params)

    respond_to do |format|
      if @mark.save
        format.html { redirect_to @mark, notice: 'Mark was successfully created.' }
        format.json { render :show, status: :created, location: @mark }
      else
        format.html { render :new }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marks/1
  # PATCH/PUT /marks/1.json
  def update
    respond_to do |format|
      if @mark.update(mark_params)
        format.html { redirect_to @mark, notice: 'Mark was successfully updated.' }
        format.json { render :show, status: :ok, location: @mark }
      else
        format.html { render :edit }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marks/1
  # DELETE /marks/1.json
  def destroy
    @mark.destroy
    respond_to do |format|
      format.html { redirect_to marks_url, notice: 'Mark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mark
      @mark = Mark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mark_params
      params.require(:mark).permit(:id,:student_id, :subject_id, :quarter, :half, :ann)
    end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  def index
  	@students = Student.all
  	@std_attd = Student.joins('join attendances ON students.sid = attendances.sid')
  	
  end

  def student
  	@students = Student.all
  end

  def management
  end

  def getStudent
  	sid = params[:sid]
  	print sid
  	
  	@student = Student.find(sid)
    @std = Student.joins(:marks)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:id, :tname, :doj, :gender, :exp, :ph, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/cls_helper.rb
module ClsHelper
end

app/helpers/exam_helper.rb
module ExamHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :tname %><br>
    <%= f.text_field :tname %>
  </div>
  <div class="field">
    <%= f.label :doj %><br>
    <%= f.date_select :doj %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :experience %><br>
    <%= f.text_field :exp %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_field :ph %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Teachers</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Tname</th>
      <th>Doj</th>
      <th>Gender</th>
      <th>Experience</th>
      <th>Contact</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.id %></td>
        <td><%= teacher.tname %></td>
        <td><%= teacher.doj %></td>
        <td><%= teacher.gender %></td>
        <td><%= teacher.exp %></td>
        <td><%= teacher.ph %></td>
        <td><%= teacher.address %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>id:</strong>
  <%= @teacher.id %>
</p>

<p>
  <strong>Tname:</strong>
  <%= @teacher.tname %>
</p>

<p>
  <strong>Doj:</strong>
  <%= @teacher.doj %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @teacher.gender %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @teacher.exp %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @teacher.ph %>
</p>

<p>
  <strong>Address:</strong>
  <%= @teacher.address %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>